#116 auditing for tables
devonfw/my-thai-star pull request #230
Opened 2019-06-11 11:01 UTC by tliszyns

2019-06-11 11:44 UTC, tliszyns commented
Why travis build failed? First I've got error `'dependencies.dependency.version' for io.oasp.java.modules:devon4j-jpa-envers:jar is missing`. After I add version in pom I've got:
`Could not resolve dependencies for project com.devonfw.java.mtsj:mtsj-core:jar:1.12.3-SNAPSHOT: Could not find artifact io.oasp.java.modules:devon4j-jpa-envers:jar:3.0.2 in central (https://repo.maven.apache.org/maven2)`

2019-06-25 16:05 UTC, hohwille requested changes
@tliszyns thanks for this PR. This looks quite good 👍 
I just added a few comments for improvement.
Some more questions:
* Dont we need the *_AUD tables for all supported DB types? Wouldn't otherwise MTS break for all other DBs?
* Did we pick the right entities/tables for auditing? IMHO all looks perfect. The only one I could question is the blob table. The orders/bookings are create "immutable" so it is perfectly correct that they are not audited.

2019-06-25 16:05 UTC, hohwille commented on java/mtsj/core/src/main/resources/db/specific/h2/V0001__R001_Create_schema.sql
> +CREATE CACHED TABLE PUBLIC.Category_AUD(
For homogenity we should either qualify all tables with schema or none. Same applies for `CACHED` keyword that is omitted in all existing create table statements. We should do that consistently within the DDL.

2019-06-26 07:34 UTC, tliszyns commented
> * Dont we need the *_AUD tables for all supported DB types? Wouldn't otherwise MTS break for all other DBs?
There are AUD tables for other DB types.

2022-09-06 17:58 UTC, closed without merging