Quarkus - Microservice dishmanagement
devonfw/my-thai-star pull request #560
Opened 2021-09-29 12:13 UTC by ssarmokadam

Please find more details below:

**Dataaccess layer:**
- Instead of criteria API I have use querydsl with code generation.
- created Frgment interface and its impl for querydsl methods and Repository extending JpaRepository for standard methods

**Logic layer**
- Followed Eto and Cto pattern as devon4j
- Removed interface and kept implementation class only

2021-10-25 16:54 UTC, GuentherJulian requested changes

2021-11-01 20:25 UTC, sobkowiak commented on quarkus/dishmanagement/src/main/java/com/devonfw/application/dishmanagement/dataaccess/repo/CategoryFragment.java
> + *
Please complete the comment

2021-11-01 20:26 UTC, sobkowiak commented on quarkus/dishmanagement/src/main/java/com/devonfw/application/dishmanagement/dataaccess/repo/IngerdientFragmentImpl.java
> + *
Please complete this TODO

2021-11-01 20:26 UTC, sobkowiak commented on quarkus/dishmanagement/src/main/java/com/devonfw/application/dishmanagement/dataaccess/repo/IngredientFragment.java
> + *
Please complete this TODO

2021-11-01 20:27 UTC, sobkowiak commented on quarkus/dishmanagement/src/main/java/com/devonfw/application/dishmanagement/dataaccess/DishEntity.java
> +  // private ImageEntity image;
Please resolve this TODO

2021-11-01 20:28 UTC, sobkowiak commented on quarkus/dishmanagement/src/main/java/com/devonfw/application/dishmanagement/dataaccess/DishEntity.java
> +// @Setter
Please remove the unused code

2021-11-01 20:33 UTC, sobkowiak commented
I assume the code under `java/dishmanagement` was an intermediate step to transit the code to a quarkus microservice and finally it should be removed, so I didn't do any review for it

2021-11-01 21:22 UTC, sobkowiak commented on quarkus/dishmanagement/src/main/java/com/devonfw/application/dishmanagement/common/to/CategoryCto.java
> +public class CategoryCto {
If there are no relations a CTO is pointless and shall be omitted. (https://github.com/devonfw/devon4j/blob/master/documentation/guide-eto-cto.asciidoc#cto)

2021-11-01 21:22 UTC, sobkowiak commented on quarkus/dishmanagement/src/main/java/com/devonfw/application/dishmanagement/common/to/IngredientCto.java
> +public class IngredientCto {
If there are no relations a CTO is pointless and shall be omitted. (https://github.com/devonfw/devon4j/blob/master/documentation/guide-eto-cto.asciidoc#cto)

2021-11-01 21:25 UTC, sobkowiak commented on quarkus/dishmanagement/src/main/java/com/devonfw/application/dishmanagement/common/ApplicationPersistenceEntity.java
> +  public int getModificationCounter() {
Why is this automatic modification counter disabled?

2021-11-01 21:26 UTC, sobkowiak commented on quarkus/dishmanagement/src/main/java/com/devonfw/application/dishmanagement/common/ApplicationPersistenceEntity.java
> +  // @Version
Why is this automatic modification counter disabled?

2021-11-01 21:48 UTC, sobkowiak commented on quarkus/dishmanagement/src/main/java/com/devonfw/application/dishmanagement/dataaccess/CategorySearchCriteriaTo.java
> +  private StringSearchConfigTo nameOption;
The `StringSearchConfigTo` attributes are actually not used in any query

2021-11-01 21:48 UTC, sobkowiak commented on quarkus/dishmanagement/src/main/java/com/devonfw/application/dishmanagement/dataaccess/DishSearchCriteriaTo.java
> +  private StringSearchConfigTo searchByOption;
The `StringSearchConfigTo` attributes are actually not used in any query

2021-11-01 21:49 UTC, sobkowiak commented on quarkus/dishmanagement/src/main/java/com/devonfw/application/dishmanagement/dataaccess/IngredientSearchCriteriaTo.java
> +  private StringSearchConfigTo descriptionOption;
The `StringSearchConfigTo` attributes are actually not used in any query

2021-11-01 22:12 UTC, sobkowiak commented on quarkus/dishmanagement/src/main/java/com/devonfw/application/dishmanagement/logic/UcDishManagement.java
> +
Please try to avoid looping through both lists looking for matches. Use Stream API instead

2021-11-01 22:13 UTC, sobkowiak commented on quarkus/dishmanagement/src/main/java/com/devonfw/application/dishmanagement/logic/UcDishManagement.java
> +    for (DishCto entity : dishEntitiesFiltered) {
Please use Streams API instead of looping through the list

2021-11-01 22:15 UTC, sobkowiak commented on quarkus/dishmanagement/src/main/java/com/devonfw/application/dishmanagement/service/rest/v1/DishManagementRestService.java
> +    return pageDishCto;
Please return the result of `findDishCtos` directly instead of using this local variable

2021-11-01 22:15 UTC, sobkowiak commented on quarkus/dishmanagement/src/main/java/com/devonfw/application/dishmanagement/service/rest/v1/DishManagementRestService.java
> +  // @CrossOrigin
Please remove the unused code

2021-11-01 22:32 UTC, sobkowiak commented
I see no test cases for the repositories, usecase and service.  Is it planned in a separate task?

2021-11-03 05:23 UTC, ssarmokadam commented
@GuentherJulian @sobkowiak I will fix this comments next week as we have multiple holidays this week... I will update here once done... Thanks for the review

2022-02-04 05:14 UTC, ssarmokadam commented
Raised new PR with changes https://github.com/devonfw/my-thai-star/pull/814 . As fork is deleted not able to continue here so closing this PR

2022-02-04 05:14 UTC, closed without merging