spellcheck changes
devonfw/my-thai-star pull request #710
Opened 2021-11-26 10:03 UTC by akanagar

2021-11-30 09:33 UTC, ssarmokadam requested changes

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/User-Stories.asciidoc
> + . the `inviter` and myself receives an email about my cancellation
inviter -> dict it is valid word

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/User-Stories.asciidoc
> +. Entered email address could be email of `inviter` or any invited guest.
same as above

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/User-Stories.asciidoc
> + .. `veggy` (yes|no|does not matter (default))
veggy -> dict

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/User-Stories.asciidoc
> + . only reservations and orders with reservation date in the future shall be available in this view. All other orders and reservation shall not be deleted; for `data analytics` those orders and reser
is data analytics detected as spell check?

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/agile.asciidoc
> +The team aligned on having two weekly `Standup` meetings instead of a Daily `Standup` meeting. In comparison with the time boxed length of `15mins` described in the CAF for this project the team exte
15mins -> try 15 mins
Standup-> Stand Up
30mins -> 30 mins

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/angular-ci.asciidoc
> +    `mavenInstallation` = 'Maven3'
ideally source should not be added to backticks ... so block between

[source]
----
// code here
----
should be ignored

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/angular-ci.asciidoc
> +`sh """yarn ${buildScript}"""`
no need of backticks here... this should be ignored by regex from .spellcheck.yml

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/angular-ci.asciidoc
> +`sh """yarn ${lintScript}"""`
same as above

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/angular-design.asciidoc
> +Group of `dialogs` with the proposal of giving some functionalities to the user, as login, register, change password or connect with Twitter.
dialogs is in dict remove backticks

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/angular-design.asciidoc
> +As the application send emails to both guests and hosts, we choose an approach based on `URL’s` where the email contain a button with an URL to a service in the app and a token, front-end read that t
URL should not be in backtick

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/angular-testing.asciidoc
> +Dialog components are in a special category because they can not be tested normally. In the way Material implements the opening of `dialogs`, you have to create a component that will load into a dial
dialogs to dict

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/java-ci.asciidoc
> +    `javaDir` = 'java/mtsj'
sourcecode should not be included in backticks

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/java-design.asciidoc
> +`auth.inMemoryAuthentication().withUser("waiter").password("waiter").roles("Waiter").and().withUser("user0").password("password").roles("Customer");`
source code should not be in backticks

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/java-design.asciidoc
> +`@RolesAllowed(Roles.WAITER)`
same as above

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/mrchecker.asciidoc
> +You must run My Thai Star `frontend` and backend application and modify your url to the front in `mrchecker/endtoend-test/src/resources/settings.properties`
frontend-> front-end or front end

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/mrchecker.asciidoc
> +`mvn test -Dtest=MyThaiStarTest -Dbrowser=Chrome`
source in between ``` do not require to be added in single backtick

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/mrchecker.asciidoc
> +`mvn test -Dtest=MyThaiStarTest -Dbrowser=ChromeHeadless`// use firefox navigator
same as above

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/my-thai-star-publish.asciidoc
> +git credentialsId:`'github-devonfw-ci'`, url:'https://github.com/devonfw/my-thai-star/'
no backticks for source

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/my-thai-star-publish.asciidoc
> +`yarn test:ci`
same as above

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/my-thai-star-publish.asciidoc
> +            git branch: 'develop', credentialsId: `'github-devonfw-ci'`, url: 'https://github.com/devonfw/my-thai-star/'
same as above

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/nodejs-design.asciidoc
> +`app.use(auth.registerAuthentication);`
same as above

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/nodejs-design.asciidoc
> +`app.get('/mythaistar/services/rest/security/v1/currentuser', auth.getCurrentUser);`
no backtick for source code

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/nodejs-design.asciidoc
> +`app.use('/mythaistar/services/rest/ordermanagement/v1/order/filter', auth.securizedEndpoint('WAITER'));
same as above

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/sap-hana-guide.asciidoc
> +`ALTER DATABASE HXE ADD 'scriptserver'`
same as above

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/traefik-reverse-proxy.asciidoc
> +    `- "traefik.http.routers.angular.rule=PathPrefix(`/`)"
same as above

2021-11-30 09:33 UTC, ssarmokadam commented on documentation/traefik-reverse-proxy.asciidoc
> +`$ docker-compose -f docker-compose.traefik.yml up -d --build`
same as above

2021-11-30 09:36 UTC, ssarmokadam commented
@akanagar  where is your updated .spellcheck.yml file?

2021-12-01 05:12 UTC, akanagar commented on documentation/User-Stories.asciidoc
> + . the `inviter` and myself receives an email about my cancellation
@ssarmokadam  Suggested changes implemented. Please check.

2021-12-01 13:21 UTC, merged